export const LOGOIMAGE = {
    // LOGO: require('../assets/images/logo.png'),
     LOGO: require('../assets/images/logo_name.png'),
}
export const ICONS = {
    emailIcon: require('../assets/images/email3x.png'),
    dialIcon: require('../assets/images/call3x.png'),
    passwordIcon: require('../assets/images/password.png'),
    checkIcon: require('../assets/images/check.png'),
    unCheckIcon: require('../assets/images/uncheck.png'),
    drawerIcon: require('../assets/images/tabIcon3x.png'),
    tickMarkIcon: require('../assets/images/tickMark.png'),
    validateIcon: require('../assets/images/validate.png'),
    registerIcon: require('../assets/images/register.png'),
    certifyIcon: require('../assets/images/certify.png'),
    dropDwnIcon: require('../assets/images/dropdown.png'),
    backIcon: require('../assets/images/arrow3x.png'),
    searchIcon: require('../assets/images/search.png'),
    servicesIcon: require('../assets/images/constructor.png'),
    crossIcon: require('../assets/images/cross.png'),
    starIcon: require('../assets/images/star3x.png'),
    emptystarIcon: require('../assets/images/startheme3x.png'),
    halfstarIcon: require('../assets/images/star_half_.png'),
    adthereIcon: require('../assets/images/message3x.png'),
    locationIcon: require('../assets/images/location3x.png'),
    videoIcon: require('../assets/images/video3x.png'),
    photoIcon: require('../assets/images/photo3x.png'),
    offersIcon: require('../assets/images/offers3x.png'),
    jobsIcon: require('../assets/images/jobs3x.png'),
    documentIcon: require('../assets/images/file3x.png'),
    reviewsIcon: require('../assets/images/startheme3x.png'),
    downArrwIcon: require('../assets/images/downArrow.png'),
    upArrwIcon: require('../assets/images/upArrow.png'),
    homeIcon: require('../assets/images/home3x.png'),
    joinIcon: require('../assets/images/join3x.png'),
    categoryIcon: require('../assets/images/category.png'),
    logoutIcon: require('../assets/images/logout.png'),
    eyeIcon: require('../assets/images/eye.png'),
    editIcon: require('../assets/images/edit.png'),
    trashIcon: require('../assets/images/trash.png'),
    plusIcon: require('../assets/images/plus.png'),
    playIcon: require('../assets/images/PlayIcon.png'),
    pause_Icon48dp: require('../assets/images/pause__white_48dp.png'),
    pause_Icon_2x: require('../assets/images/pause_Icon_2x.png'),
    website_Icon: require('../assets/images/website_Icon3x.png'),
    pause_Icon_new: require('../assets/images/pause_Icon_new.png'),
    mic_On_Icon: require('../assets/images/mic_Onicon.png'),
    mic_Off_Icon: require('../assets/images/mic_off_ICON.png'),
    city_Icon: require('../assets/images/city_ICON.png'),
    map_Icon: require('../assets/images/map_Icon3x.png'),
    search_New: require('../assets/images/search_new.png'),
    close_New: require('../assets/images/close_New.png')
}
