export const LOGOIMAGE = {
    LOGO: require('../assets/images/logo.png'),
}
export const ICONS = {
    emailIcon: require('../assets/images/email.png'),
    dialIcon: require('../assets/images/call.png'),
    passwordIcon: require('../assets/images/password.png'),
    checkIcon: require('../assets/images/check.png'),
    unCheckIcon: require('../assets/images/uncheck.png'),
    drawerIcon: require('../assets/images/tabIcon.png'),
    tickMarkIcon: require('../assets/images/tickMark.png'),
    validateIcon: require('../assets/images/validate.png'),
    registerIcon: require('../assets/images/register.png'),
    certifyIcon: require('../assets/images/certify.png'),
    dropDwnIcon: require('../assets/images/dropdown.png'),
    backIcon: require('../assets/images/arrow.png'),
    searchIcon: require('../assets/images/search.png'),
    servicesIcon: require('../assets/images/constructor.png'),
    crossIcon: require('../assets/images/cross.png'),
    starIcon: require('../assets/images/star.png'),
    adthereIcon: require('../assets/images/message.png'),
    locationIcon: require('../assets/images/location.png'),
    videoIcon: require('../assets/images/video.png'),
    photoIcon: require('../assets/images/photo.png'),
    offersIcon: require('../assets/images/offers.png'),
    jobsIcon: require('../assets/images/jobs.png'),
    documentIcon: require('../assets/images/file.png'),
    reviewsIcon: require('../assets/images/startheme.png'),
    downArrwIcon: require('../assets/images/downArrow.png'),
    upArrwIcon: require('../assets/images/upArrow.png'),
    homeIcon: require('../assets/images/home.png'),
    joinIcon: require('../assets/images/join.png'),
    categoryIcon: require('../assets/images/category.png'),
    logoutIcon: require('../assets/images/logout.png'),
    eyeIcon: require('../assets/images/eye.png'),
    editIcon: require('../assets/images/edit.png'),
    trashIcon: require('../assets/images/trash.png'),
    plusIcon: require('../assets/images/plus.png'),
    playIcon: require('../assets/images/PlayIcon.png'),
    pause_Icon48dp: require('../assets/images/pause__white_48dp.png'),
    pause_Icon_2x: require('../assets/images/pause_Icon_2x.png'),
    website_Icon: require('../assets/images/website_Icon.png'),
    pause_Icon_new: require('../assets/images/pause_Icon_new.png'),
    mic_On_Icon: require('../assets/images/mic_Onicon.png'),
    mic_Off_Icon: require('../assets/images/mic_off_ICON.png'),
    city_Icon: require('../assets/images/city_ICON.png'),
}
